const userData = [
  {
    id: 1,
    status: 'alumni',
    imgUrl: 'http://source.unsplash.com/random/?portrait',
    name: 'Jan Grade',
    title: 'Software Developer & Coach',
    company: 'neuefische GmbH',
    country: 'Lüneburg, Germany',
    email: 'hello@jangrade.de,',
    capstoneProject: 'Language App',
    personalWebsite: 'www.jangrade.de',
    github: 'github.com/jangrade',
    codepen: 'codepen',
    skills: ['react', 'html', 'css', 'sass', 'bootstrap', 'javascript'],
  },
  {
    id: 2,
    status: 'alumni',
    imgUrl: 'http://source.unsplash.com/random/?portrait',
    name: 'Kevin Kuhfeldt',
    title: 'Frontend Developer',
    company: 'Eventim',
    country: 'Hamburg, Germany',
    email: 'kevin.kuhfeldt@gmx.de',
    capstoneProject: 'Bitcoin App',
    personalWebsite: 'personal-website',
    github: 'github.com/evinku',
    codepen: 'codepen',
    skills: ['react', 'html', 'css', 'sass', 'bootstrap', 'javascript'],
  },
  {
    id: 3,
    status: 'alumni',
    imgUrl: './img/natalie.jpg',
    name: 'Natalie Fuchs',
    title: 'Frontend Developer',
    company: 'Argonauten GmbH',
    country: 'Hamburg, Germany',
    email: 'natalie.fuchs@argonauten.de',
    capstoneProject: 'Stadt, Land, Fuchs App',
    personalWebsite: 'personal-website',
    github: 'github',
    codepen: 'codepen',
    skills: ['react', 'html', 'css', 'sass', 'bootstrap', 'javascript'],
  },
  {
    id: 4,
    status: 'new',
    imgUrl: 'http://source.unsplash.com/random/?portrait',
    name: 'Nicole Frydrych',
    title: 'Web Developer',
    company: 'neuefische',
    country: 'Berlin, Germany',
    email: 'nicole.fr91@gmx.de',
    capstoneProject: 'Vegan App',
    personalWebsite: 'personal-website',
    github: 'github.com/nicolefrydrych',
    codepen: 'codepen',
    skills: ['react', 'html', 'css', 'sass', 'bootstrap', 'javascript'],
  },
]

export default userData
