const userData = [
  {
    id: 1,
    status: 'alumni',
    imgUrl: './img/natalie-square.jpg',
    name: 'Natalie Fuchs',
    title: 'Frontend Developer',
    company: 'Argonauten GmbH',
    country: 'Hamburg, Germany',
    email: 'natalie.fuchs@argonauten.de',
    capstoneName: 'Stadt, Land, Fuchs App',
    capstoneLink: 'https://github.com/ntlfox/stadt-land-name',
    personalWebsite: 'https://github.com/ntlfox/personal-website',
    github: 'https://github.com/ntlfox',
    codepen: 'https://codepen.io/ntlfox/',
    skills: ['react', 'html', 'css', 'sass', 'bootstrap', 'javascript'],
    isToggled: false,
  },
  {
    id: 2,
    status: 'alumni',
    imgUrl: './img/kevin.png',
    name: 'Kevin Kuhfeldt',
    title: 'Frontend Developer',
    company: 'Eventim',
    country: 'Hamburg, Germany',
    email: 'kevin.kuhfeldt@gmx.de',
    capstoneName: 'CryptoFolio App',
    capstoneLink: 'https://github.com/evinku/cryptofolio',
    personalWebsite: 'https://github.com/evinku/personal-website',
    github: 'https://github.com/evinku',
    codepen: '',
    skills: ['react', 'html', 'css', 'sass', 'javascript'],
    isToggled: false,
  },
  {
    id: 3,
    status: 'alumni',
    imgUrl: './img/jan.jpg',
    name: 'Jan Grade',
    title: 'Software Developer & Coach',
    company: 'neuefische GmbH',
    country: 'Lüneburg, Germany',
    email: 'hello@jangrade.de,',
    capstoneName: 'Language App',
    capstoneLink: '',
    personalWebsite: 'https://jangrade.de',
    github: 'https://github.com/jangrade',
    codepen: '',
    skills: ['react', 'javascript'],
    isToggled: false,
  },
  {
    id: 4,
    status: 'new',
    imgUrl: './img/nicole.jpg',
    name: 'Nicole Frydrych',
    title: 'Web Developer',
    company: 'neuefische',
    country: 'Berlin, Germany',
    email: 'nicole.fr91@gmx.de',
    capstoneName: 'Vegan App',
    capstoneLink: 'https://github.com/nicolefrydrych/capstone-project',
    personalWebsite: '',
    github: 'https://github.com/nicolefrydrych',
    codepen: '',
    skills: ['html', 'bootstrap', 'css', 'sass', 'javascript', 'react'],
    isToggled: false,
  },
]

export default userData
